"""R10 and R11 of #383: the context header on a project, and its dependencies.

**R10.** Every open project carries a header, generated rather than written, so
a reader sees the family before the body. Owner, 2026-09-24: *"The context
should be identical for the parent and the work package, so it is always the
parent and its children."* The header is derived from facts with homes of their
own: sub-issues, the `Phase` and `Route` fields, the milestone, an open pull
request, and GitHub's own dependency links. It is a view of those, never a
second copy to maintain, which is why it sits between markers and is rewritten
whole.

**R11.** A *Dependencies and related work* section that says `waits on #N` or
`is needed by #N` has declared a dependency, and the header only shows the ones GitHub knows. So a declaration
with no matching link is reported: the prose argues, the link is the fact.
Only those two phrases count, because they are the vocabulary `CLAUDE.md`
gives a dependency; *related* and *touches* are not dependencies.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from typing import Mapping, Sequence

from .model import Issue, ParentProject, Project, PullRequest

START = "<!-- context: generated by scripts/board-context.py; edits here are overwritten -->"
END = "<!-- /context -->"

_BLOCK = re.compile(re.escape(START.split(";")[0]) + r".*?" + re.escape(END) + r"\n*",
                    re.S)

# `#400 MAIN PROJECT: TLE Scheduler`, `#400 WP A Del 1 of 1, pt 1 of 2: Scheduler core`
_PREFIX = re.compile(r"^#(\d+)\s+(MAIN PROJECT|WP\s+([A-Z]+)[^:]*):\s*")


def short_title(title: str, outside: bool = False) -> str:
    """The name without the family prefix, keeping the package letter.

    `outside` keeps the parent's number on a package from another family:
    inside its own header `WP C` is unambiguous, beside other projects it
    reads `Additional Game Lifecycle (#71 WP C)`.
    """
    m = _PREFIX.match(title)
    if not m:
        return title
    rest = title[m.end():]
    if not m.group(3):
        return rest
    if outside:
        return f"{rest} (#{m.group(1)} WP {m.group(3)})"
    return f"WP {m.group(3)}: {rest}"


def strip(body: str) -> str:
    """The body without its generated header."""
    return _BLOCK.sub("", body, count=1)


def family_root(issue: Issue, board: Mapping[int, Issue]) -> Issue:
    parent = board.get(issue.raw.parent) if issue.raw.parent else None
    return parent if parent is not None else issue


def family(root: Issue, board: Mapping[int, Issue]) -> list[Issue]:
    members = [root]
    if isinstance(root, ParentProject):
        members += [board[n] for n in root.work_packages if n in board]
    return members


_REFS = re.compile(r"\b(?:Refs|Closes|Fixes)\s+#(\d+)", re.I)
_LEAD = re.compile(r"^#(\d+)\b")


def open_prs(board: Mapping[int, Issue]) -> dict[int, list[int]]:
    """Issue number to the open pull requests that name it.

    A pull request names its issue in its title (`#414 Scheduler core`) or with
    a `Refs`/`Closes` line in its body; either counts.
    """
    out: dict[int, list[int]] = {}
    for pr in board.values():
        if not isinstance(pr, PullRequest) or pr.state != "OPEN":
            continue
        named = set(int(n) for n in _REFS.findall(pr.body))
        m = _LEAD.match(pr.title)
        if m:
            named.add(int(m.group(1)))
        for n in named:
            out.setdefault(n, []).append(pr.number)
    return {n: sorted(v) for n, v in out.items()}


def _cell(value: str | None) -> str:
    # A title with a pipe in it would split the table row.
    return value.replace("|", "\\|") if value else "—"


_DATED = re.compile(r"^## Context as of .*\n\n?", re.M)


def as_of(day: date) -> str:
    """`## Context as of Thursday 24 September 2026`."""
    return f"## Context as of {day:%A} {day.day} {day:%B %Y}"


def undated(header: str | None) -> str | None:
    """A header with its date taken out, for asking whether the facts moved.

    **The date is not a fact about the family**, so a header is stale when its
    content differs, never because a day has passed. Rewriting on the date
    alone would edit every project daily, and each edit moves `updatedAt`,
    which R1 falls back on for *N days quiet*.
    """
    return None if header is None else _DATED.sub("", header, count=1)


def render(root: Issue, board: Mapping[int, Issue],
           titles: Mapping[int, str], day: date | None = None) -> str:
    """The header for a family, identical on every member.

    `titles` resolves a dependency outside the open board — a closed issue a
    project waits on still needs its name shown. `day` is when it was written.
    """
    members = family(root, board)
    prs = open_prs(board)
    rows = ["| | phase | route | milestone | pull request |",
            "| --- | --- | --- | --- | --- |"]
    for m in members:
        # A parent carries no route and no milestone (CLAUDE.md), so any that
        # is set on one is ignored rather than shown as if it meant something.
        is_parent = isinstance(m, ParentProject)
        route = None if is_parent else m.field("Route")
        milestone = None if is_parent else m.raw.milestone
        pr = ", ".join(f"#{n}" for n in prs.get(m.number, []))
        phase = m.field("Phase")
        if m.state == "CLOSED":
            phase = f"{phase}, closed" if phase else "closed"
        rows.append(f"| {_cell(f'#{m.number} {short_title(m.title)}')} | {_cell(phase)} "
                    f"| {_cell(route)} | {_cell(milestone)} | {_cell(pr)} |")

    inside = {m.number for m in members}
    waits = sorted({n for m in members for n in m.raw.blocked_by} - inside)
    needed = sorted({n for m in members for n in m.raw.blocks} - inside)

    def names(numbers: Sequence[int]) -> str:
        if not numbers:
            return "none"
        return " · ".join(f"#{n} {short_title(titles.get(n, ''), outside=True)}".rstrip()
                          for n in numbers)

    lines = [START, as_of(day or date.today()), "", *rows, "",
             f"Waits on: {names(waits)}",
             f"Needed by: {names(needed)}",
             END]
    return "\n".join(lines)


INTRODUCTION = "## Introduction"


def with_header(body: str, header: str) -> str:
    """The body with this header on top, and the text under it titled.

    A body that opens with prose gets `## Introduction` above it, so the
    header's heading does not read as the title of the body's first paragraph.
    One that already opens with a heading keeps it.
    """
    rest = strip(body).lstrip("\n")
    if rest and not rest.startswith("#"):
        rest = f"{INTRODUCTION}\n\n{rest}"
    return header + "\n\n" + rest


def current(issue: Issue) -> str | None:
    """The header the body carries now, or None."""
    m = _BLOCK.search(issue.body)
    return m.group(0).rstrip("\n") if m else None


def missing_members(board: Mapping[int, Issue]) -> list[int]:
    """Work packages of an open parent that the open board does not hold.

    Closed ones, in practice. They still belong in the header -- a family is
    all its packages, delivered or not -- so they are fetched and listed, and
    never written to: a closed issue is history and is not edited.
    """
    return sorted({n for i in board.values() if isinstance(i, ParentProject)
                   for n in i.work_packages if n not in board})


def wanted_titles(projects: Sequence[Issue]) -> set[int]:
    return {n for p in projects for n in (*p.raw.blocked_by, *p.raw.blocks)}


def headers(board: Mapping[int, Issue], titles: Mapping[int, str],
            day: date | None = None) -> dict[int, str]:
    """Every open project's header, by issue number."""
    out: dict[int, str] = {}
    for issue in board.values():
        if not isinstance(issue, Project) or issue.state != "OPEN":
            continue
        out[issue.number] = render(family_root(issue, board), board, titles, day)
    return out


def needs_writing(issue: Issue, header: str) -> bool:
    """Missing, out of date in its facts, or its text below untitled."""
    have = current(issue)
    return (have is None or not _DATED.search(have)
            or undated(have) != undated(header)
            or strip(issue.body).lstrip("\n")[:1] not in ("#", ""))


def fields_visible(board: Mapping[int, Issue]) -> bool:
    """Whether the token that fetched this board can see issue fields at all.

    A token that cannot answers with no fields rather than an error, and a
    header written from that shows every phase as blank — on every project,
    and looking entirely deliberate. Checked on the population, not per issue:
    one project with no Phase is plausible, all of them is the token.
    """
    projects = [i for i in board.values() if isinstance(i, Project)]
    return any(p.field("Phase") for p in projects) if projects else True


def stale(board: Mapping[int, Issue],
          titles: Mapping[int, str]) -> list[tuple[int, str]]:
    """Open projects whose header is missing or out of date."""
    found = []
    for number, header in sorted(headers(board, titles).items()):
        have = current(board[number])
        if have is None:
            found.append((number, "no header"))
        elif undated(have) != undated(header):
            found.append((number, "out of date"))
        elif not _DATED.search(have):
            found.append((number, "undated"))
        elif strip(board[number].body).lstrip("\n")[:1] not in ("#", ""):
            found.append((number, "the text below it has no heading"))
    return found


# --------------------------------------------------------------------------
# R11: declared in the body, missing from GitHub
# --------------------------------------------------------------------------

# Read from this section only. Scanning the whole body found `waits on #253` in
# #71's table of placements, which is #251's dependency and not #71's.
DEPENDENCIES = "Dependencies and related work"

_DECLARED = re.compile(
    r"\b(waits on|is needed by)\s+((?:#\d+(?:\s+R\d+)?(?:\s*(?:,|and|&)\s*)?)+)",
    re.I)


@dataclass(frozen=True)
class Missing:
    number: int
    phrase: str     # "waits on" | "is needed by"
    other: int


def declared(body: str) -> list[tuple[str, int]]:
    """Every `waits on #N` and `is needed by #N` in a body, header excluded."""
    out = []
    for m in _DECLARED.finditer(strip(body)):
        phrase = m.group(1).lower()
        for n in re.findall(r"#(\d+)", m.group(2)):
            out.append((phrase, int(n)))
    return out


def undeclared_links(board: Mapping[int, Issue]) -> list[Missing]:
    """Dependencies a project's body states that GitHub does not hold."""
    found = []
    for issue in sorted(board.values(), key=lambda i: i.number):
        if not isinstance(issue, Project) or issue.state != "OPEN":
            continue
        for phrase, other in declared(issue.section(DEPENDENCIES)):
            if other == issue.number:
                continue
            held = issue.raw.blocked_by if phrase == "waits on" else issue.raw.blocks
            if other not in held:
                found.append(Missing(issue.number, phrase, other))
    # One finding per pair, however many times the body repeats it.
    return sorted(set(found), key=lambda f: (f.number, f.other, f.phrase))


def render_findings(stale_found: Sequence[tuple[int, str]],
                    links: Sequence[Missing],
                    colour: bool = True) -> str:
    bold = (lambda s: f"\033[1m{s}\033[0m") if colour else (lambda s: s)
    dim = (lambda s: f"\033[2m{s}\033[0m") if colour else (lambda s: s)
    red = (lambda s: f"\033[31m{s}\033[0m") if colour else (lambda s: s)
    green = (lambda s: f"\033[32m{s}\033[0m") if colour else (lambda s: s)

    out = [f"{bold('CONTEXT')}  {dim('R10 — the generated header on each open project')}"]
    if not stale_found:
        out.append(f"  {green('ok')} {dim('every open project carries a current header')}")
    for number, why in stale_found:
        out.append(f"  {red('!!')} {bold(f'#{number}')} {dim(why + ' — scripts/board-context.py --write')}")

    out += ["", f"{bold('DEPENDENCIES')}  {dim('R11 — declared in the body, held by GitHub')}"]
    if not links:
        out.append(f"  {green('ok')} {dim('every waits on / is needed by is a GitHub link')}")
    for f in links:
        out.append(f"  {red('!!')} {bold(f'#{f.number}')} {f.phrase} #{f.other}  "
                   f"{dim('not a GitHub dependency')}")
    return "\n".join(out)

