#!/usr/bin/env python3
"""comment-inventory.py — the reasoning in the tooling, listed so it cannot be lost.

#383. Forty-one per cent of the delivery tooling is comment, citing 67 issues
and carrying dated incidents. That half cannot be re-derived by reading the
code, so any restructuring has to place it rather than replace it, and this is
the checklist that proves it was placed.

**The dated ones are the test list.** Each records a defect that actually
happened, with its evidence already written. A model that reintroduces one of
them is wrong, and the comment says how to know.

    scripts/comment-inventory.py                 # summary to stdout
    scripts/comment-inventory.py --write PATH    # the full inventory as markdown
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ISSUE = re.compile(r"#(\d{1,4})\b")
DATE = re.compile(r"\b(20\d\d-\d\d-\d\d)\b")
# `name() {`, `function name`, `def name(`
DEF = re.compile(r"^\s*(?:function\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*\(\)\s*\{|^\s*def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")

FILES = [
    "scripts/deploy.sh",
    "scripts/verify.sh",
]


def comment_of(line: str) -> str | None:
    """The comment text, or None. Only whole-line comments: a trailing one is
    usually a restatement of the code, and the reasoning lives in the blocks."""
    stripped = line.strip()
    if stripped.startswith("#") and not stripped.startswith("#!"):
        return stripped.lstrip("#").strip()
    return None


def blocks(path: Path):
    """Contiguous comment blocks, with the definition each one precedes."""
    lines = path.read_text().splitlines()
    out, current, start = [], [], 0
    for i, line in enumerate(lines, 1):
        text = comment_of(line)
        if text is not None:
            if not current:
                start = i
            current.append(text)
            continue
        if current:
            # what does this block introduce? the next definition, if the gap
            # is small enough that it is plausibly about it
            owner = ""
            for j in range(i - 1, min(i + 3, len(lines))):
                match = DEF.match(lines[j]) if j < len(lines) else None
                if match:
                    owner = match.group(1) or match.group(2)
                    break
            out.append((start, i - 1, owner, current))
            current = []
    if current:
        out.append((start, len(lines), "", current))
    return out


def collect():
    rows = []
    for name in FILES:
        path = Path(name)
        if not path.exists():
            continue
        for start, end, owner, body in blocks(path):
            text = " ".join(body)
            issues = sorted({int(n) for n in ISSUE.findall(text)})
            dates = sorted(set(DATE.findall(text)))
            if not issues and not dates:
                continue
            rows.append({
                "file": name, "start": start, "end": end, "owner": owner,
                "issues": issues, "dates": dates, "lines": body,
            })
    return rows


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", type=Path, help="write the inventory here")
    args = parser.parse_args(argv)

    rows = collect()
    dated = [r for r in rows if r["dates"]]
    issues = sorted({n for r in rows for n in r["issues"]})

    print(f"{len(rows)} comment blocks carry an issue or a date")
    print(f"  {len(dated)} carry a date — these are the regression list")
    print(f"  {len(issues)} distinct issues cited")
    for name in FILES:
        mine = [r for r in rows if r["file"] == name]
        if mine:
            lines = sum(len(r["lines"]) for r in mine)
            print(f"  {name:32s} {len(mine):3d} blocks, {lines:4d} lines, "
                  f"{sum(1 for r in mine if r['dates']):2d} dated")

    if not args.write:
        return 0

    parts = [
        "<!-- markdownlint-disable-file MD013 MD033 -->",
        "# Comment inventory: the reasoning in the delivery tooling",
        "",
        "Generated by `scripts/comment-inventory.py`. **Do not edit by hand** —",
        "re-run it. #383.",
        "",
        "Each block below is comment that cites an issue or records a date. The",
        "dated ones record a defect that actually happened and are the regression",
        "list any replacement must satisfy.",
        "",
        f"| | |", "| --- | --- |",
        f"| blocks carrying an issue or a date | {len(rows)} |",
        f"| of those, dated | {len(dated)} |",
        f"| distinct issues cited | {len(issues)} |",
        "",
        "## The regression list",
        "",
        "Every dated block, which is every defect this tooling is known to have",
        "survived. A replacement that reintroduces one of these is wrong.",
        "",
        "| date | where | what it explains | issues |",
        "| --- | --- | --- | --- |",
    ]
    for r in sorted(dated, key=lambda r: (r["dates"][0], r["file"])):
        where = f"`{r['file'].split('/')[-1]}:{r['start']}`"
        owner = f"`{r['owner']}`" if r["owner"] else "—"
        first = next((line for line in r["lines"]
                       if line.strip("- ") and not set(line) <= set("- ")), "")
        first = first[:110].replace("|", "\\|")
        cited = ", ".join(f"#{n}" for n in r["issues"]) or "—"
        parts.append(f"| {r['dates'][0]} | {where} {owner} | {first} | {cited} |")

    parts += ["", "## Every block, in file order", ""]
    for name in FILES:
        mine = [r for r in rows if r["file"] == name]
        if not mine:
            continue
        parts += [f"### `{name}`", ""]
        for r in mine:
            head = f"**{name.split('/')[-1]}:{r['start']}–{r['end']}**"
            if r["owner"]:
                head += f" · `{r['owner']}`"
            if r["issues"]:
                head += " · " + ", ".join(f"#{n}" for n in r["issues"])
            if r["dates"]:
                head += " · " + ", ".join(r["dates"])
            # a fenced block, not a blockquote: these comments contain their
            # own markdown -- headings, tables, emphasis -- and quoting them
            # renders it, which both lies about the source and trips the linter
            parts += [head, "", "```text"] + r["lines"] + ["```", ""]

    text = "\n".join(parts).rstrip() + "\n"
    args.write.write_text(text)
    print(f"\nWrote {args.write}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
