#!/usr/bin/env python3
"""document-map.py — every heading in docs/, in one place.

**Why it exists.** `one fact, one home` is a rule about where a fact belongs,
and it is unusable without knowing all the homes. `CLAUDE.md`'s *Where the
detail is* has five rows against ~600 headings, so the practical answer to
"where does this go?" was a grep for the words about to be written — which
finds pages that already use those words and says nothing about ownership.
Four facts were written into the wrong place on 2026-09-07 (#349).

**Derived, never edited.** Regenerated and committed like `docs/1.5`, so it
cannot drift from what it describes. `--check` exits 1 if the file on disk is
not what would be generated, which is what CI asks.

**It also reports duplicate headings** — the one part that needs no judgement.
`docs/3.3` carried two `2.13.2`s, found only because something happened to link
to one of them; two branches each added a `2.5.1` a week later.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "1.6-document-map.md"

# Fenced blocks hold `#` comments in bash and `#` headings in nothing, so a
# line inside one is never a heading. Missing this counted every shell comment
# in every example as a section.
FENCE = re.compile(r"^\s*```")
HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*$")


def headings(path: Path):
    out, fenced = [], False
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if FENCE.match(line):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = HEADING.match(line)
        if m:
            out.append((len(m.group(1)), m.group(2), n))
    return out


def gloss(path: Path) -> str:
    """The document's first real sentence, as its one-line description."""
    fenced = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if FENCE.match(line):
            fenced = not fenced
            continue
        if fenced or not line.strip() or line.startswith(("#", "|", ">", "-", "*", "!")):
            continue
        text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", line.strip())
        text = text.replace("**", "").replace("`", "")
        return (text.split(". ")[0].rstrip(".") + ".")[:160]
    return ""


def build():
    files = sorted(DOCS.glob("*.md"), key=lambda p: p.name)
    files = [f for f in files if f.name != OUT.name]
    lines = [
        "# 1.6 Document map",
        "",
        "**Generated by `scripts/document-map.py`. Do not edit.**",
        "",
        "Every heading in `docs/`, so a fact can be looked up rather than",
        "grepped for. The rule this serves is *one fact, one home*",
        "([3.6](3.6-change-lifecycle.md)); the rule was never the gap, knowing",
        "all the homes was — see #349.",
        "",
        "**Before adding text to a document, find its subject here and go",
        "there.** Adding it where the editing happens to be is what this exists",
        "to stop.",
        "",
    ]
    total = 0
    for f in files:
        hs = headings(f)
        total += len(hs)
        g = gloss(f)
        lines.append(f"## [{f.name}]({f.name})")
        lines.append("")
        if g:
            # A blockquote, not `*emphasis*`: markdownlint reads a lone
            # emphasised line as a heading pretending not to be one (MD036),
            # and this file must lint clean like `docs/1.5`.
            lines.append(f"> {g}")
            lines.append("")
        sections = [h for h in hs if h[0] > 1]
        for depth, text, _n in sections:
            # `- 3. Notes` reads as an ordered list item numbered 3 and fails
            # MD029, because most section headings here start with a number.
            safe = re.sub(r"^(\d+)\.", r"\1\\.", text)
            lines.append(f"{'  ' * (depth - 2)}- {safe}")
        # A document that is all tables — `3.0-tools` — has a gloss and no
        # sections, and the gloss already left a blank line. Adding another
        # doubles it (MD012). Tested on `sections`, not `hs`: `hs` carries the
        # document's own H1 and is therefore never empty, which is how this was
        # wrong the first time.
        if not (g and not sections):
            lines.append("")
    lines.insert(
        4, f"**{total} headings in {len(files)} documents.**\n"
    )
    return "\n".join(lines).rstrip() + "\n", files


def duplicates(files):
    """A heading text appearing in more than one place, across all documents.

    Reported per text, because the numbering is what collides: two `2.13.2`s in
    one file, or a `2.5.1` added on two branches.
    """
    seen = {}
    for f in files:
        for depth, text, n in headings(f):
            # Depth 1 is the document's own title. A section sharing a title
            # with a document — `Database Schema` in 2.7 and 4.2 — is worth
            # knowing and is not this: it is a judgement about scope, where a
            # repeated *section* is a plain collision. Reporting both would mix
            # a certainty with an opinion, and the opinion is the noisier.
            if depth == 1:
                continue
            seen.setdefault(text, []).append(f"{f.name}:{n}")
    return {t: w for t, w in seen.items() if len(w) > 1}


def main():
    text, files = build()
    dups = duplicates(files)
    check = "--check" in sys.argv

    if dups:
        print("duplicate headings:", file=sys.stderr)
        for t, where in sorted(dups.items()):
            print(f"  {t!r} — {', '.join(where)}", file=sys.stderr)

    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"error: {OUT.name} is out of date — run document-map.py --write", file=sys.stderr)
            return 1
        return 1 if dups else 0

    if "--write" in sys.argv:
        OUT.write_text(text, encoding="utf-8")
        print(f"document-map: wrote {OUT.relative_to(ROOT)}")
    else:
        sys.stdout.write(text)
    return 1 if dups else 0


if __name__ == "__main__":
    sys.exit(main())
